[package]
name = "brute"
version = "0.1.0"
authors = ["Yechan Bae <yechan@gatech.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ccl = "5.1.5"
sha2 = "0.8.0"
rand = "0.7"
